### ISSUE TITLE
Custom installation failure

### ISSUE THREAD

**Issue by brainboost** [WebGateConsultingAG/CloudeeCMS#32]
During Backend stack creation using CloudFormationDeployment_CustomInstallation.yaml, without a custom domain and certificate, I'm getting 

> Resource handler returned message: User: arn:aws:sts::1234567890:assumed-role/example-cloudformationdeployer-role/AWSCloudFormation is not authorized to perform: lambda:TagResource on resource: arn:aws:lambda:eu-west-1:1234567890:function:CloudeeCmsStack-Backend-scmsfileapi-f7Z213YxEPoC because no identity-based policy allows the lambda:TagResource action

The backend stack is in ROLLBACK_COMPLETE state, all functions seem deleted, the CodeDeploy re-run brought no result. 
I also tried to add line `- lambda:TagResource` to the deployer policy, but then it failed even earlied, on the front stack creation.

**Comment by ThisIsWebGoat** [comment]
Thank you for notifying us about this!

The policy in the CloudFormation template indeed needed an update to work with changes introduced by AWS.
We've updated it in the repository to include lambda:TagResource.

Additionally, the configuration for S3 buckets also needs some changes to work with the way ACLs now work. You will notice this in the frontend build pipeline, failing to upload the compiled app to the newly created S3 buckets due to ACL settings. Until we release an updated version (probably next week), you can work around this by unchecking "block all public access" manually on the affected bucket, change object ownership -> enable ACLs and then restart the frontend codebuild pipeline.

If you have further questions, you can reach us in the CloudeeCMS slack.

**Comment by ThisIsWebGoat** [comment]
@brainboost in the TEST branch you will now find updated CF templates with S3 bucket settings adjusted to allow public access, just like before AWS introduced a change that made all buckets private by default. It enables ACLs to retain backwards compatibility. New installation should now deploy successfully.

**Comment by ThisIsWebGoat** [comment]
CF templates updated. New installation now deploys without errors again.

**Comment by brainboost** [comment]
Confirmed, the issue had fixed, thank you!
